name: docker
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [x86_64, i686, i386, armhf, aarch64]
        exclude:
          - os: linux
            arch: i386
          - os: darwin
            arch: i686
          - os: darwin
            arch: armhf
          - os: darwin
            arch: aarch64
      fail-fast: false
    steps:
      - name: Install libraries
        run: sudo apt-get install ruby-bundler bison git libonig-dev
      - uses: actions/checkout@v2
      - run: bundle install -j$(nproc)

      - name: Integration test
        run: bundle exec rake test:integration
        if: (matrix.os == 'linux' && matrix.arch == 'x86_64') || startsWith(github.ref, 'refs/tags/')

      - name: Build ${{ matrix.os }}-${{ matrix.arch }} binary
        run: bundle exec rake release:build:${{ matrix.os }}-${{ matrix.arch }} release:compress

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
        if: startsWith(github.ref, 'refs/tags/')
      - name: Upload Release Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mitamae-build/mitamae-${{ matrix.arch }}-${{ matrix.os }}.tar.gz
          asset_name: mitamae-${{ matrix.arch }}-${{ matrix.os }}.tar.gz
          asset_content_type: application/gzip
        if: startsWith(github.ref, 'refs/tags/')
      - name: Upload Release Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mitamae-build/mitamae-${{ matrix.arch }}-${{ matrix.os }}
          asset_name: mitamae-${{ matrix.arch }}-${{ matrix.os }}
          asset_content_type: application/octet-stream
        if: startsWith(github.ref, 'refs/tags/')
