name: docker
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux-x86_64
          - linux-i686
          - linux-armhf
          - linux-aarch64
          - darwin-x86_64
          - darwin-i386
      fail-fast: false
    steps:
      - name: Install libraries
        run: sudo apt-get install ruby-bundler bison git libonig-dev
      - uses: actions/checkout@v2
      - run: bundle install -j$(nproc)

      - name: Integration test
        run: bundle exec rake test:integration
        if: matrix.target == 'linux-x86_64' || startsWith(github.ref, 'refs/tags/')

      - name: Build ${{ matrix.target }} binary
        run: bundle exec rake release:build:${{ matrix.target }} release:compress

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - name: Upload Release Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mitamae-build/mitamae-${{ matrix.target }}.tar.gz
          asset_name: mitamae-${{ matrix.target }}.tar.gz
          asset_content_type: application/gzip
      - name: Upload Release Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mitamae-build/mitamae-${{ matrix.target }}
          asset_name: mitamae-${{ matrix.target }}
          asset_content_type: application/octet-stream
